-- Seed: 10 users + 120 orders
INSERT INTO users (name, email) VALUES ('User 1', 'user1@demo.test') ON DUPLICATE KEY UPDATE name=VALUES(name);
INSERT INTO users (name, email) VALUES ('User 2', 'user2@demo.test') ON DUPLICATE KEY UPDATE name=VALUES(name);
INSERT INTO users (name, email) VALUES ('User 3', 'user3@demo.test') ON DUPLICATE KEY UPDATE name=VALUES(name);
INSERT INTO users (name, email) VALUES ('User 4', 'user4@demo.test') ON DUPLICATE KEY UPDATE name=VALUES(name);
INSERT INTO users (name, email) VALUES ('User 5', 'user5@demo.test') ON DUPLICATE KEY UPDATE name=VALUES(name);
INSERT INTO users (name, email) VALUES ('User 6', 'user6@demo.test') ON DUPLICATE KEY UPDATE name=VALUES(name);
INSERT INTO users (name, email) VALUES ('User 7', 'user7@demo.test') ON DUPLICATE KEY UPDATE name=VALUES(name);
INSERT INTO users (name, email) VALUES ('User 8', 'user8@demo.test') ON DUPLICATE KEY UPDATE name=VALUES(name);
INSERT INTO users (name, email) VALUES ('User 9', 'user9@demo.test') ON DUPLICATE KEY UPDATE name=VALUES(name);
INSERT INTO users (name, email) VALUES ('User 10', 'user10@demo.test') ON DUPLICATE KEY UPDATE name=VALUES(name);

-- Reruns stay deterministic: wipe child rows first (users/products use INSERT IGNORE).
-- (DELETE + AUTO_INCREMENT reset instead of TRUNCATE, so a least-privilege user can reseed.)
DELETE FROM order_items;
DELETE FROM orders;
DELETE FROM products;
ALTER TABLE orders AUTO_INCREMENT = 1;
ALTER TABLE order_items AUTO_INCREMENT = 1;
ALTER TABLE products AUTO_INCREMENT = 1;

INSERT INTO orders (user_id, total, status) VALUES (1, 187.00, 'paid');
INSERT INTO orders (user_id, total, status) VALUES (2, 324.00, 'shipped');
INSERT INTO orders (user_id, total, status) VALUES (3, 461.00, 'cancelled');
INSERT INTO orders (user_id, total, status) VALUES (4, 598.00, 'pending');
INSERT INTO orders (user_id, total, status) VALUES (5, 735.00, 'paid');
INSERT INTO orders (user_id, total, status) VALUES (6, 872.00, 'shipped');
INSERT INTO orders (user_id, total, status) VALUES (7, 109.00, 'cancelled');
INSERT INTO orders (user_id, total, status) VALUES (8, 246.00, 'pending');
INSERT INTO orders (user_id, total, status) VALUES (9, 383.00, 'paid');
INSERT INTO orders (user_id, total, status) VALUES (10, 520.00, 'shipped');
INSERT INTO orders (user_id, total, status) VALUES (1, 657.00, 'cancelled');
INSERT INTO orders (user_id, total, status) VALUES (2, 794.00, 'pending');
INSERT INTO orders (user_id, total, status) VALUES (3, 931.00, 'paid');
INSERT INTO orders (user_id, total, status) VALUES (4, 168.00, 'shipped');
INSERT INTO orders (user_id, total, status) VALUES (5, 305.00, 'cancelled');
INSERT INTO orders (user_id, total, status) VALUES (6, 442.00, 'pending');
INSERT INTO orders (user_id, total, status) VALUES (7, 579.00, 'paid');
INSERT INTO orders (user_id, total, status) VALUES (8, 716.00, 'shipped');
INSERT INTO orders (user_id, total, status) VALUES (9, 853.00, 'cancelled');
INSERT INTO orders (user_id, total, status) VALUES (10, 90.00, 'pending');
INSERT INTO orders (user_id, total, status) VALUES (1, 227.00, 'paid');
INSERT INTO orders (user_id, total, status) VALUES (2, 364.00, 'shipped');
INSERT INTO orders (user_id, total, status) VALUES (3, 501.00, 'cancelled');
INSERT INTO orders (user_id, total, status) VALUES (4, 638.00, 'pending');
INSERT INTO orders (user_id, total, status) VALUES (5, 775.00, 'paid');
INSERT INTO orders (user_id, total, status) VALUES (6, 912.00, 'shipped');
INSERT INTO orders (user_id, total, status) VALUES (7, 149.00, 'cancelled');
INSERT INTO orders (user_id, total, status) VALUES (8, 286.00, 'pending');
INSERT INTO orders (user_id, total, status) VALUES (9, 423.00, 'paid');
INSERT INTO orders (user_id, total, status) VALUES (10, 560.00, 'shipped');
INSERT INTO orders (user_id, total, status) VALUES (1, 697.00, 'cancelled');
INSERT INTO orders (user_id, total, status) VALUES (2, 834.00, 'pending');
INSERT INTO orders (user_id, total, status) VALUES (3, 71.00, 'paid');
INSERT INTO orders (user_id, total, status) VALUES (4, 208.00, 'shipped');
INSERT INTO orders (user_id, total, status) VALUES (5, 345.00, 'cancelled');
INSERT INTO orders (user_id, total, status) VALUES (6, 482.00, 'pending');
INSERT INTO orders (user_id, total, status) VALUES (7, 619.00, 'paid');
INSERT INTO orders (user_id, total, status) VALUES (8, 756.00, 'shipped');
INSERT INTO orders (user_id, total, status) VALUES (9, 893.00, 'cancelled');
INSERT INTO orders (user_id, total, status) VALUES (10, 130.00, 'pending');
INSERT INTO orders (user_id, total, status) VALUES (1, 267.00, 'paid');
INSERT INTO orders (user_id, total, status) VALUES (2, 404.00, 'shipped');
INSERT INTO orders (user_id, total, status) VALUES (3, 541.00, 'cancelled');
INSERT INTO orders (user_id, total, status) VALUES (4, 678.00, 'pending');
INSERT INTO orders (user_id, total, status) VALUES (5, 815.00, 'paid');
INSERT INTO orders (user_id, total, status) VALUES (6, 52.00, 'shipped');
INSERT INTO orders (user_id, total, status) VALUES (7, 189.00, 'cancelled');
INSERT INTO orders (user_id, total, status) VALUES (8, 326.00, 'pending');
INSERT INTO orders (user_id, total, status) VALUES (9, 463.00, 'paid');
INSERT INTO orders (user_id, total, status) VALUES (10, 600.00, 'shipped');
INSERT INTO orders (user_id, total, status) VALUES (1, 737.00, 'cancelled');
INSERT INTO orders (user_id, total, status) VALUES (2, 874.00, 'pending');
INSERT INTO orders (user_id, total, status) VALUES (3, 111.00, 'paid');
INSERT INTO orders (user_id, total, status) VALUES (4, 248.00, 'shipped');
INSERT INTO orders (user_id, total, status) VALUES (5, 385.00, 'cancelled');
INSERT INTO orders (user_id, total, status) VALUES (6, 522.00, 'pending');
INSERT INTO orders (user_id, total, status) VALUES (7, 659.00, 'paid');
INSERT INTO orders (user_id, total, status) VALUES (8, 796.00, 'shipped');
INSERT INTO orders (user_id, total, status) VALUES (9, 933.00, 'cancelled');
INSERT INTO orders (user_id, total, status) VALUES (10, 170.00, 'pending');
INSERT INTO orders (user_id, total, status) VALUES (1, 307.00, 'paid');
INSERT INTO orders (user_id, total, status) VALUES (2, 444.00, 'shipped');
INSERT INTO orders (user_id, total, status) VALUES (3, 581.00, 'cancelled');
INSERT INTO orders (user_id, total, status) VALUES (4, 718.00, 'pending');
INSERT INTO orders (user_id, total, status) VALUES (5, 855.00, 'paid');
INSERT INTO orders (user_id, total, status) VALUES (6, 92.00, 'shipped');
INSERT INTO orders (user_id, total, status) VALUES (7, 229.00, 'cancelled');
INSERT INTO orders (user_id, total, status) VALUES (8, 366.00, 'pending');
INSERT INTO orders (user_id, total, status) VALUES (9, 503.00, 'paid');
INSERT INTO orders (user_id, total, status) VALUES (10, 640.00, 'shipped');
INSERT INTO orders (user_id, total, status) VALUES (1, 777.00, 'cancelled');
INSERT INTO orders (user_id, total, status) VALUES (2, 914.00, 'pending');
INSERT INTO orders (user_id, total, status) VALUES (3, 151.00, 'paid');
INSERT INTO orders (user_id, total, status) VALUES (4, 288.00, 'shipped');
INSERT INTO orders (user_id, total, status) VALUES (5, 425.00, 'cancelled');
INSERT INTO orders (user_id, total, status) VALUES (6, 562.00, 'pending');
INSERT INTO orders (user_id, total, status) VALUES (7, 699.00, 'paid');
INSERT INTO orders (user_id, total, status) VALUES (8, 836.00, 'shipped');
INSERT INTO orders (user_id, total, status) VALUES (9, 73.00, 'cancelled');
INSERT INTO orders (user_id, total, status) VALUES (10, 210.00, 'pending');
INSERT INTO orders (user_id, total, status) VALUES (1, 347.00, 'paid');
INSERT INTO orders (user_id, total, status) VALUES (2, 484.00, 'shipped');
INSERT INTO orders (user_id, total, status) VALUES (3, 621.00, 'cancelled');
INSERT INTO orders (user_id, total, status) VALUES (4, 758.00, 'pending');
INSERT INTO orders (user_id, total, status) VALUES (5, 895.00, 'paid');
INSERT INTO orders (user_id, total, status) VALUES (6, 132.00, 'shipped');
INSERT INTO orders (user_id, total, status) VALUES (7, 269.00, 'cancelled');
INSERT INTO orders (user_id, total, status) VALUES (8, 406.00, 'pending');
INSERT INTO orders (user_id, total, status) VALUES (9, 543.00, 'paid');
INSERT INTO orders (user_id, total, status) VALUES (10, 680.00, 'shipped');
INSERT INTO orders (user_id, total, status) VALUES (1, 817.00, 'cancelled');
INSERT INTO orders (user_id, total, status) VALUES (2, 54.00, 'pending');
INSERT INTO orders (user_id, total, status) VALUES (3, 191.00, 'paid');
INSERT INTO orders (user_id, total, status) VALUES (4, 328.00, 'shipped');
INSERT INTO orders (user_id, total, status) VALUES (5, 465.00, 'cancelled');
INSERT INTO orders (user_id, total, status) VALUES (6, 602.00, 'pending');
INSERT INTO orders (user_id, total, status) VALUES (7, 739.00, 'paid');
INSERT INTO orders (user_id, total, status) VALUES (8, 876.00, 'shipped');
INSERT INTO orders (user_id, total, status) VALUES (9, 113.00, 'cancelled');
INSERT INTO orders (user_id, total, status) VALUES (10, 250.00, 'pending');
INSERT INTO orders (user_id, total, status) VALUES (1, 387.00, 'paid');
INSERT INTO orders (user_id, total, status) VALUES (2, 524.00, 'shipped');
INSERT INTO orders (user_id, total, status) VALUES (3, 661.00, 'cancelled');
INSERT INTO orders (user_id, total, status) VALUES (4, 798.00, 'pending');
INSERT INTO orders (user_id, total, status) VALUES (5, 935.00, 'paid');
INSERT INTO orders (user_id, total, status) VALUES (6, 172.00, 'shipped');
INSERT INTO orders (user_id, total, status) VALUES (7, 309.00, 'cancelled');
INSERT INTO orders (user_id, total, status) VALUES (8, 446.00, 'pending');
INSERT INTO orders (user_id, total, status) VALUES (9, 583.00, 'paid');
INSERT INTO orders (user_id, total, status) VALUES (10, 720.00, 'shipped');
INSERT INTO orders (user_id, total, status) VALUES (1, 857.00, 'cancelled');
INSERT INTO orders (user_id, total, status) VALUES (2, 94.00, 'pending');
INSERT INTO orders (user_id, total, status) VALUES (3, 231.00, 'paid');
INSERT INTO orders (user_id, total, status) VALUES (4, 368.00, 'shipped');
INSERT INTO orders (user_id, total, status) VALUES (5, 505.00, 'cancelled');
INSERT INTO orders (user_id, total, status) VALUES (6, 642.00, 'pending');
INSERT INTO orders (user_id, total, status) VALUES (7, 779.00, 'paid');
INSERT INTO orders (user_id, total, status) VALUES (8, 916.00, 'shipped');
INSERT INTO orders (user_id, total, status) VALUES (9, 153.00, 'cancelled');
INSERT INTO orders (user_id, total, status) VALUES (10, 290.00, 'pending');

-- Seed: 20 products + 120 order_items (deterministic pattern, unique pairs)
INSERT INTO products (name, price) VALUES ('Hanoi Coffee Beans', 12.50) ON DUPLICATE KEY UPDATE price=VALUES(price);
INSERT INTO products (name, price) VALUES ('Pho Spice Kit', 8.99) ON DUPLICATE KEY UPDATE price=VALUES(price);
INSERT INTO products (name, price) VALUES ('Banh Mi Maker', 24.00) ON DUPLICATE KEY UPDATE price=VALUES(price);
INSERT INTO products (name, price) VALUES ('Fish Sauce Premium', 6.75) ON DUPLICATE KEY UPDATE price=VALUES(price);
INSERT INTO products (name, price) VALUES ('Silk Scarf', 29.90) ON DUPLICATE KEY UPDATE price=VALUES(price);
INSERT INTO products (name, price) VALUES ('Bamboo Straw Set', 4.50) ON DUPLICATE KEY UPDATE price=VALUES(price);
INSERT INTO products (name, price) VALUES ('Ceramic Teapot', 32.00) ON DUPLICATE KEY UPDATE price=VALUES(price);
INSERT INTO products (name, price) VALUES ('Ao Dai Mini', 19.90) ON DUPLICATE KEY UPDATE price=VALUES(price);
INSERT INTO products (name, price) VALUES ('Lacquer Bowl', 15.25) ON DUPLICATE KEY UPDATE price=VALUES(price);
INSERT INTO products (name, price) VALUES ('Conical Hat', 9.90) ON DUPLICATE KEY UPDATE price=VALUES(price);
INSERT INTO products (name, price) VALUES ('Coconut Candy', 5.50) ON DUPLICATE KEY UPDATE price=VALUES(price);
INSERT INTO products (name, price) VALUES ('Cashew Nuts 500g', 11.00) ON DUPLICATE KEY UPDATE price=VALUES(price);
INSERT INTO products (name, price) VALUES ('Drip Filter Set', 7.25) ON DUPLICATE KEY UPDATE price=VALUES(price);
INSERT INTO products (name, price) VALUES ('Tea Sampler Box', 14.75) ON DUPLICATE KEY UPDATE price=VALUES(price);
INSERT INTO products (name, price) VALUES ('Chopsticks Pair', 3.99) ON DUPLICATE KEY UPDATE price=VALUES(price);
INSERT INTO products (name, price) VALUES ('Rice Paper Pack', 2.50) ON DUPLICATE KEY UPDATE price=VALUES(price);
INSERT INTO products (name, price) VALUES ('Lemongrass Oil', 9.25) ON DUPLICATE KEY UPDATE price=VALUES(price);
INSERT INTO products (name, price) VALUES ('Notebook Kraft', 4.99) ON DUPLICATE KEY UPDATE price=VALUES(price);
INSERT INTO products (name, price) VALUES ('Tote Canvas', 6.50) ON DUPLICATE KEY UPDATE price=VALUES(price);
INSERT INTO products (name, price) VALUES ('Sticker Pack', 1.99) ON DUPLICATE KEY UPDATE price=VALUES(price);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (1, 1, 1, 12.50);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (2, 2, 2, 8.99);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (3, 3, 3, 24.00);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (4, 4, 4, 6.75);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (5, 5, 1, 29.90);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (6, 6, 2, 4.50);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (7, 7, 3, 32.00);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (8, 8, 4, 19.90);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (9, 9, 1, 15.25);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (10, 10, 2, 9.90);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (11, 11, 3, 5.50);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (12, 12, 4, 11.00);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (13, 13, 1, 7.25);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (14, 14, 2, 14.75);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (15, 15, 3, 3.99);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (16, 16, 4, 2.50);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (17, 17, 1, 9.25);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (18, 18, 2, 4.99);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (19, 19, 3, 6.50);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (20, 20, 4, 1.99);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (21, 1, 1, 12.50);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (22, 2, 2, 8.99);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (23, 3, 3, 24.00);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (24, 4, 4, 6.75);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (25, 5, 1, 29.90);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (26, 6, 2, 4.50);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (27, 7, 3, 32.00);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (28, 8, 4, 19.90);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (29, 9, 1, 15.25);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (30, 10, 2, 9.90);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (31, 11, 3, 5.50);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (32, 12, 4, 11.00);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (33, 13, 1, 7.25);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (34, 14, 2, 14.75);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (35, 15, 3, 3.99);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (36, 16, 4, 2.50);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (37, 17, 1, 9.25);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (38, 18, 2, 4.99);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (39, 19, 3, 6.50);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (40, 20, 4, 1.99);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (41, 1, 1, 12.50);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (42, 2, 2, 8.99);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (43, 3, 3, 24.00);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (44, 4, 4, 6.75);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (45, 5, 1, 29.90);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (46, 6, 2, 4.50);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (47, 7, 3, 32.00);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (48, 8, 4, 19.90);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (49, 9, 1, 15.25);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (50, 10, 2, 9.90);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (51, 11, 3, 5.50);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (52, 12, 4, 11.00);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (53, 13, 1, 7.25);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (54, 14, 2, 14.75);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (55, 15, 3, 3.99);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (56, 16, 4, 2.50);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (57, 17, 1, 9.25);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (58, 18, 2, 4.99);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (59, 19, 3, 6.50);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (60, 20, 4, 1.99);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (61, 1, 1, 12.50);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (62, 2, 2, 8.99);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (63, 3, 3, 24.00);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (64, 4, 4, 6.75);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (65, 5, 1, 29.90);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (66, 6, 2, 4.50);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (67, 7, 3, 32.00);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (68, 8, 4, 19.90);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (69, 9, 1, 15.25);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (70, 10, 2, 9.90);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (71, 11, 3, 5.50);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (72, 12, 4, 11.00);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (73, 13, 1, 7.25);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (74, 14, 2, 14.75);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (75, 15, 3, 3.99);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (76, 16, 4, 2.50);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (77, 17, 1, 9.25);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (78, 18, 2, 4.99);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (79, 19, 3, 6.50);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (80, 20, 4, 1.99);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (81, 1, 1, 12.50);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (82, 2, 2, 8.99);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (83, 3, 3, 24.00);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (84, 4, 4, 6.75);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (85, 5, 1, 29.90);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (86, 6, 2, 4.50);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (87, 7, 3, 32.00);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (88, 8, 4, 19.90);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (89, 9, 1, 15.25);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (90, 10, 2, 9.90);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (91, 11, 3, 5.50);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (92, 12, 4, 11.00);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (93, 13, 1, 7.25);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (94, 14, 2, 14.75);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (95, 15, 3, 3.99);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (96, 16, 4, 2.50);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (97, 17, 1, 9.25);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (98, 18, 2, 4.99);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (99, 19, 3, 6.50);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (100, 20, 4, 1.99);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (101, 1, 1, 12.50);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (102, 2, 2, 8.99);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (103, 3, 3, 24.00);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (104, 4, 4, 6.75);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (105, 5, 1, 29.90);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (106, 6, 2, 4.50);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (107, 7, 3, 32.00);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (108, 8, 4, 19.90);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (109, 9, 1, 15.25);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (110, 10, 2, 9.90);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (111, 11, 3, 5.50);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (112, 12, 4, 11.00);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (113, 13, 1, 7.25);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (114, 14, 2, 14.75);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (115, 15, 3, 3.99);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (116, 16, 4, 2.50);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (117, 17, 1, 9.25);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (118, 18, 2, 4.99);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (119, 19, 3, 6.50);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (120, 20, 4, 1.99);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (1, 1, 1, 12.50);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (2, 2, 2, 8.99);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (3, 3, 3, 24.00);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (4, 4, 4, 6.75);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (5, 5, 1, 29.90);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (6, 6, 2, 4.50);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (7, 7, 3, 32.00);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (8, 8, 4, 19.90);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (9, 9, 1, 15.25);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (10, 10, 2, 9.90);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (11, 11, 3, 5.50);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (12, 12, 4, 11.00);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (13, 13, 1, 7.25);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (14, 14, 2, 14.75);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (15, 15, 3, 3.99);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (16, 16, 4, 2.50);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (17, 17, 1, 9.25);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (18, 18, 2, 4.99);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (19, 19, 3, 6.50);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (20, 20, 4, 1.99);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (21, 1, 1, 12.50);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (22, 2, 2, 8.99);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (23, 3, 3, 24.00);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (24, 4, 4, 6.75);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (25, 5, 1, 29.90);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (26, 6, 2, 4.50);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (27, 7, 3, 32.00);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (28, 8, 4, 19.90);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (29, 9, 1, 15.25);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (30, 10, 2, 9.90);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (31, 11, 3, 5.50);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (32, 12, 4, 11.00);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (33, 13, 1, 7.25);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (34, 14, 2, 14.75);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (35, 15, 3, 3.99);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (36, 16, 4, 2.50);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (37, 17, 1, 9.25);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (38, 18, 2, 4.99);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (39, 19, 3, 6.50);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (40, 20, 4, 1.99);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (41, 1, 1, 12.50);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (42, 2, 2, 8.99);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (43, 3, 3, 24.00);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (44, 4, 4, 6.75);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (45, 5, 1, 29.90);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (46, 6, 2, 4.50);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (47, 7, 3, 32.00);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (48, 8, 4, 19.90);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (49, 9, 1, 15.25);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (50, 10, 2, 9.90);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (51, 11, 3, 5.50);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (52, 12, 4, 11.00);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (53, 13, 1, 7.25);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (54, 14, 2, 14.75);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (55, 15, 3, 3.99);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (56, 16, 4, 2.50);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (57, 17, 1, 9.25);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (58, 18, 2, 4.99);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (59, 19, 3, 6.50);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (60, 20, 4, 1.99);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (61, 1, 1, 12.50);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (62, 2, 2, 8.99);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (63, 3, 3, 24.00);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (64, 4, 4, 6.75);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (65, 5, 1, 29.90);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (66, 6, 2, 4.50);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (67, 7, 3, 32.00);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (68, 8, 4, 19.90);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (69, 9, 1, 15.25);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (70, 10, 2, 9.90);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (71, 11, 3, 5.50);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (72, 12, 4, 11.00);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (73, 13, 1, 7.25);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (74, 14, 2, 14.75);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (75, 15, 3, 3.99);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (76, 16, 4, 2.50);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (77, 17, 1, 9.25);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (78, 18, 2, 4.99);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (79, 19, 3, 6.50);
INSERT IGNORE INTO order_items (order_id, product_id, qty, unit_price) VALUES (80, 20, 4, 1.99);
